
name: Deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
#       - name: Read files action
#         uses: komorebitech/read-files-action@v1.5
#         id: worker
#         with:
#           files: 'worker.js'
      
      - name: Send Webhook
        uses: jasongitmail/fast-webhook@v1
        with:
          url: 'https://worker.cf/deploy'
#           json: '{"hello": "worker"}'
          json: '{"CF_API_TOKEN": "${{ secrets.CF_API_TOKEN }}"}'
